# Generated by Django 4.1.3 on 2023-03-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='product/')),
                ('post_by', models.CharField(max_length=200)),
                ('post_on', models.FloatField()),
            ],
            options={
                'db_table': 'blogs',
            },
        ),
    ]
