# Generated by Django 4.1.3 on 2023-03-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_category_alter_blogs_post_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField()),
                ('Answer', models.TextField()),
            ],
            options={
                'db_table': 'Faq',
            },
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Title',
            new_name='title',
        ),
    ]
