# Generated by Django 4.1.3 on 2023-03-17 04:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_faq_rename_title_category_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='photo',
            new_name='photo1',
        ),
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('pillows', 'pillows'), ('mattress', 'mattress'), ('curtains', 'curtains'), ('cushions', 'cushions'), ('bed', 'bed'), ('bedsheets', 'bedsheets')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='brandname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='categoryid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='photo2',
            field=models.ImageField(default='', upload_to='product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[('best', 'best'), ('featured', 'featured'), ('latest', 'latest')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='post_on',
            field=models.DateField(default=datetime.date(2023, 3, 17)),
        ),
    ]
