# Generated by Django 4.1.3 on 2023-04-13 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_blogs_post_on_likenow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='photo1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='mrp',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='post_on',
            field=models.DateField(default=datetime.date(2023, 4, 13)),
        ),
    ]
