# Generated by Django 4.1.3 on 2023-04-14 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_product_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='likenow',
            old_name='productid',
            new_name='productsid',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='post_on',
            field=models.DateField(default=datetime.date(2023, 4, 14)),
        ),
        migrations.AlterModelTable(
            name='products',
            table='products',
        ),
    ]
