# Generated by Django 4.1.3 on 2023-04-25 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_signup_alter_blogs_post_on'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signup',
            new_name='subscribe',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='post_on',
            field=models.DateField(default=datetime.date(2023, 4, 25)),
        ),
        migrations.AlterModelTable(
            name='subscribe',
            table='subscribe',
        ),
    ]
