# Generated by Django 4.1.3 on 2023-04-26 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rename_signup_subscribe_alter_blogs_post_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='post_on',
            field=models.DateField(default=datetime.date(2023, 4, 26)),
        ),
    ]
